"""Helper lists for various purposes."""

skip_delete_extensions = [
    "aar",
    "appimage",
    "cab",
    "chi",
    "chm",
    "chq",
    "chw",
    "crx",
    "deb",
    "docm",
    "docx",
    "edb",
    "edp",
    "edr",
    "esd",
    "exe",
    "ipa",
    "iso",
    "lib",
    "msi",
    "nsi",
    "nsis",
    "pptm",
    "pptx",
    "rpm",
    "s7z",
    "sitx",
    "swm",
    "ear",
    "jar",
    "war",
    "xlsm",
    "xlsx",
    "xpi",
    "zipx",
]


skip_delete_mimetypes = [
    "application/java-archive",
    "application/vnd.android.package-archive",
    "application/vnd.debian.binary-package",
    "application/vnd.ms-cab-compressed",
    "application/vnd.ms-htmlhelp",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/x-chrome-extension",
    "application/x-iso9660-image",
    "application/x-ole-storage",
    "application/x-rpm",
    "application/x-sitx",
    "application/x-stuffitx",
    "application/x-xpinstall",
]
