"""Enumeration of warning types."""

from enum import Enum


class WarningTypes(Enum):
    """Enumeration of warning types."""

    MAX_DEPTH = "MAX_DEPTH"
    MAX_ARCHIVE_SIZE_BYTES = "MAX_ARCHIVE_SIZE_BYTES"
    MAX_TOTAL_SIZE_BYTES = "MAX_TOTAL_SIZE_BYTES"
    MIN_ARCHIVE_RATIO = "MIN_ARCHIVE_RATIO"
    MIN_DISK_FREE_SPACE = "MIN_DISK_FREE_SPACE"
    NO_ARCHIVER = "NO_ARCHIVER"
    MISSING_ARCHIVER = "MISSING_ARCHIVER"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    SIZE_RETRIEVAL_FAILED = "SIZE_RETRIEVAL_FAILED"
    DELETE_FAILED = "DELETE_FAILED"
    SKIP_DELETE_EXTENSION = "SKIP_DELETE_EXTENSION"
    SKIP_DELETE_MIMETYPE = "SKIP_DELETE_MIMETYPE"
